{ pkgs, modulesPath, ... }:
{
  # Setup nix.
  nix = {
    settings = {
      auto-optimise-store = true;
      experimental-features = [ "nix-command" "flakes" ];
      keep-outputs = true;
    };
    gc = {
      automatic = true;
      dates = "weekly";
      options = "--delete-older-than 1w";
    };
  };

  nixpkgs.hostPlatform = "aarch64-linux";
  networking.hostName = "orbstack-linux";

  # Setup time & keyboard input.
  time.timeZone = "Asia/Bangkok";
  i18n.defaultLocale = "en_US.UTF-8";

  # The configs above are usually defined in ../shared but are included here
  # because this is a standalone config for Orbstack.

  environment.systemPackages = with pkgs; [
    killall
  ];

  # Install git required for flakes.
  # Once home-manager is run, system git is discarded.
  programs.git = {
    enable = true;
    package = pkgs.gitMinimal;
  };

  # Config starting from this point is generated by Orbstack 1.4.3.

  imports = [
    # Include the default lxd configuration.
    "${modulesPath}/virtualisation/lxc-container.nix"
    # Include the container-specific autogenerated configuration.
    /etc/nixos/lxd.nix
    /etc/nixos/orbstack.nix
  ];

  # https://nixos.wiki/wiki/FAQ/When_do_I_update_stateVersion
  system.stateVersion = "21.05";

  # As this is intended as a stadalone image, undo some of the minimal profile stuff.
  documentation.enable = true;
  documentation.nixos.enable = true;
  environment.noXlibs = false;
}
