" Every now and then, I use vim without any plugins to get away from all the
" formatters, linters, completions and fuzzy-finders.
"
" It's like meditation. It's not all fun but much needed and brings me peace.

color zaibatsu

" Turn on syntax-highlighting.
syntax on

" Relative number line with current line number showed instead of default 0.
set number relativenumber

" Do not highlight matching parens.
let g:loaded_matchparen = 1

" Automatically set the working director to that of currently opened file.
set autochdir
