
-- -- Enable OSC 52 on Linux.
-- if vim.uv.os_uname().sysname == "Linux" then
--   vim.g.clipboard = {
--     name = "OSC 52",
--     copy = {
--       ["+"] = require("vim.ui.clipboard.osc52").copy("+"),
--       ["*"] = require("vim.ui.clipboard.osc52").copy("*"),
--     },
--   }
-- end
